const uiText={ja:{uploadTitle:"写真でみる",uploadHelp:"猫の写真をえらんでください。あとでAIをつなげられる形にしてあります。",uploadButtonText:"写真をえらぶ",previewPlaceholder:"ここに写真が表示されます",manualTitle:"手動でえらぶ",manualHelp:"AIがまちがっても、あとで手でなおせるようにします。",gestureLabel:"しぐさ",showResultButton:"結果を見る",resultTitle:"結果",resultEmpty:"まだ結果はありません",emptySelect:"-- えらんでください --",resultMaybe:"気持ちの可能性",resultAdvice:"おすすめ",resultSource:"出典",noSelection:"先にしぐさをえらんでください。"},en:{uploadTitle:"See by Photo",uploadHelp:"Choose a cat photo. This app is prepared so AI can be added later.",uploadButtonText:"Choose a photo",previewPlaceholder:"Your photo will appear here",manualTitle:"Choose Manually",manualHelp:"If AI is wrong later, you can fix it by hand.",gestureLabel:"Gesture",showResultButton:"Show Result",resultTitle:"Result",resultEmpty:"No result yet",emptySelect:"-- Please choose --",resultMaybe:"Possible feeling",resultAdvice:"Advice",resultSource:"Sources",noSelection:"Please choose a gesture first."},th:{uploadTitle:"ดูจากรูปภาพ",uploadHelp:"เลือกรูปแมวได้เลย แอปนี้เตรียมไว้ให้ต่อ AI เพิ่มทีหลังได้",uploadButtonText:"เลือกรูปภาพ",previewPlaceholder:"รูปภาพจะแสดงที่นี่",manualTitle:"เลือกเอง",manualHelp:"ถ้า AI เดาผิดภายหลัง ผู้ใช้ยังแก้เองได้",gestureLabel:"ท่าทาง",showResultButton:"ดูผลลัพธ์",resultTitle:"ผลลัพธ์",resultEmpty:"ยังไม่มีผลลัพธ์",emptySelect:"-- กรุณาเลือก --",resultMaybe:"ความรู้สึกที่เป็นไปได้",resultAdvice:"คำแนะนำ",resultSource:"แหล่งอ้างอิง",noSelection:"กรุณาเลือกท่าทางก่อน"}};
let currentLanguage="ja";let gestureData=[];
const imageInput=document.getElementById("imageInput"),previewImage=document.getElementById("previewImage"),previewPlaceholder=document.getElementById("previewPlaceholder"),languageSelect=document.getElementById("languageSelect"),gestureSelect=document.getElementById("gestureSelect"),showResultButton=document.getElementById("showResultButton"),resultBox=document.getElementById("resultBox");
function setText(id,val){const e=document.getElementById(id);if(e)e.textContent=val}
function applyLanguage(){const t=uiText[currentLanguage];["uploadTitle","uploadHelp","uploadButtonText","previewPlaceholder","manualTitle","manualHelp","gestureLabel","showResultButton","resultTitle"].forEach(id=>setText(id,t[id]));if(!resultBox.dataset.hasResult){resultBox.innerHTML=`<p id="resultEmpty">${t.resultEmpty}</p>`}renderGestureOptions()}
function renderGestureOptions(){const t=uiText[currentLanguage],currentValue=gestureSelect.value;gestureSelect.innerHTML="";const def=document.createElement("option");def.value="";def.textContent=t.emptySelect;gestureSelect.appendChild(def);gestureData.forEach(item=>{const opt=document.createElement("option");opt.value=item.gesture_key;opt.textContent=item[`gesture_name_${currentLanguage}`];gestureSelect.appendChild(opt)});gestureSelect.value=currentValue||""}
function showImagePreview(file){const reader=new FileReader();reader.onload=(event)=>{previewImage.src=event.target.result;previewImage.hidden=false;previewPlaceholder.hidden=true};reader.readAsDataURL(file)}
function renderResult(item){const t=uiText[currentLanguage];resultBox.dataset.hasResult="true";resultBox.innerHTML=`<div class="result-item"><h3>${item[`gesture_name_${currentLanguage}`]}</h3><p><strong>${t.resultMaybe}:</strong> ${item.emotion_primary}</p><p>${item[`summary_${currentLanguage}`]}</p><p><strong>${t.resultAdvice}:</strong> ${item[`advice_${currentLanguage}`]}</p><p class="meta">${item[`citation_note_${currentLanguage}`]}</p><p><strong>${t.resultSource}:</strong></p><ul class="source-list">${item.source_titles.map(s=>`<li>${s}</li>`).join("")}</ul></div>`}
async function loadGestureData(){const response=await fetch("./data/gestures.json");gestureData=await response.json();renderGestureOptions()}
imageInput.addEventListener("change",()=>{const file=imageInput.files[0];if(file)showImagePreview(file)});
languageSelect.addEventListener("change",e=>{currentLanguage=e.target.value;applyLanguage()});
showResultButton.addEventListener("click",()=>{const key=gestureSelect.value;if(!key){alert(uiText[currentLanguage].noSelection);return}const item=gestureData.find(i=>i.gesture_key===key);if(item)renderResult(item)});
if("serviceWorker" in navigator){window.addEventListener("load",()=>{navigator.serviceWorker.register("./service-worker.js").catch(err=>console.log("Service worker registration failed:",err))})}
loadGestureData().then(applyLanguage);
